apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp-rc
spec:
  replicas: 5
  selector:
    app: goapp-pod
  template:
    metadata:
      name: goapp
      labels:
        app: goapp-pod
    spec:
      containers:
        - name: goapp-container
          image: dangtong/goapp
          ports:
            - containerPort: 8080
