apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-dynamic
spec:
  resources:
    requests:
      storage: 80Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "fast"
