apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata: 
  name: fast 
provisioner: ebs.csi.aws.com 
volumeBindingMode: Immediate 
reclaimPolicy: Retain 
parameters: 
  csi.storage.k8s.io/fstype: ext4 
  type: gp3
allowedTopologies: 
- matchLabelExpressions:
    - key: topology.ebs.csi.aws.com/zone
      values:
        - ap-northeast-2a 
        - ap-northeast-2c