apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  labels:
    name: liveness
spec:
  containers:
  - name: liveness-container
    image: k8s.gcr.io/liveness
    args:
      - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awsome
      initialDelaySeconds: 3
      periodSeconds: 3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
