apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
spec:
  selector:
    matchLabels:
      app: fortune
  replicas: 3
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: html-generator
        image: dangtong/fortunek8s
        volumeMounts:
        - name: html
          mountPath: /var/htdocs
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: web-server
        image: nginx:alpine
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
      volumes:
      - name: html
        emptyDir: {}
