apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deploy
spec:
  selector:
    matchLabels:
      app: nodeapp-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeapp-pod
    spec:
      containers:
      - name: nodeapp-deploy
        image: dangtong/nodeapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
spec:
  type: NodePort
  selector:
    app: nodeapp-pod
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30123